const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http'],
}

const outputFile = './swagger_output.json'
const endpointsFiles = ["./index.js"]

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index.js')
})